### ISSUE TITLE
Puppet 4.x-only modules and Gemfile

### ISSUE THREAD

**Issue by reidmv** [voxpupuli/modulesync_config#102]
Currently the Gemfile template will include the Puppet 3.x gem. There does not appear to be a way to parameterize what version of the Puppet gem is included on a per-module basis. This causes problems when trying to integrate a Puppet 4.x-only module into modulesync. See https://github.com/voxpupuli/puppet-dotnet/pull/9/files#r53225512.

Is this a problem? If so, how should it be resolved?

**Comment by igalic** [comment]
I definitely think it's a problem that should be solved
similarly, we have lots of modules that don't do any acceptance tests, but sync Gems and spec/acceptance for them.

I don't know *how* to solve it yet, though.
maybe a global option in .sync.yml?
