### ISSUE TITLE
.travis.yml allowed_failures?

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/modulesync_config#114]
Looking at this build:

https://travis-ci.org/voxpupuli/puppet-nodejs/builds/122684685

Should we test ruby 2.3.0 outside of the allowed_failures block? It looks like it failed. Is this the expected result?

**Comment by rnelson0** [comment]
Build .7 is rubocop (should pass) and .8 is test (allow failure), two
different tests. We could probably make this easier to see by stripping
everything but the CHECK var from the rubocop test's env, but this appears
to be working as advertised for now - there's blown up rubocop in them thar
CI runs!

>

-- 

Rob Nelson
rnelson0@gmail.com
