### ISSUE TITLE
Add .github templates in moduleroot

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/modulesync_config#121]
https://github.com/blog/2111-issue-and-pull-request-templates

We should determine what to add for these.

**Comment by igalic** [comment]
i thought we had those in plumbing: https://github.com/voxpupuli/plumbing/blob/master/share/canned_responses/close_inactivity maybe we should move them here then?

**Comment by jyaworski** [comment]
@igalic it would definitely be better, in my opinion. Then they would get synced out to each project.

**Comment by igalic** [comment]
:+1:
