### ISSUE TITLE
Consider using rubocop-rspec

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/modulesync_config#122]
https://github.com/nevir/rubocop-rspec

This would help with our spec tests.

**Comment by igalic** [comment]
does this have less obnoxious defaults?

**Comment by rnelson0** [comment]
Less obnoxious than rubocop?

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by jyaworski** [comment]
This _is_ rubocop, so.... let's try it?

**Comment by rnelson0** [comment]
How about we try it in a single module before adding it to module sync?

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by jyaworski** [comment]
I nominate either collectd or mcollective. Those have a lot of tests.

**Comment by rnelson0** [comment]
:+1: make it so!

**Comment by jyaworski** [comment]
https://github.com/voxpupuli/puppet-collectd/pull/487

**Comment by jyaworski** [comment]
It looks like the defaults may be fairly obnoxious. Please take a look.

**Comment by jyaworski** [comment]
Ping @igalic @bastelfreak @rnelson0 opinions on the PR referenced above? This looks sane.
