### ISSUE TITLE
Set target ruby version in rubocop

### ISSUE THREAD

**Issue by jyaworski** [voxpupuli/modulesync_config#138]
1.9.3 may be a good one:

https://github.com/bbatsov/rubocop#setting-the-target-ruby-version

**Comment by juniorsysadmin** [comment]
I thought Rubocop only worked on 2.2.0 and above

**Comment by bastelfreak** [comment]
noooooooo 1.9.3 /o\
We can set it to 2.3.0? We already test at this version and rubocop supports it.

**Comment by juniorsysadmin** [comment]
Possibly a tad early for 2.3.x

**Comment by bastelfreak** [comment]
Why early? It got released almost 5 months ago, we run the rubocop rake task already only on 2.3 and I'm not aware of any issues in one of our modules.

**Comment by jyaworski** [comment]
From https://github.com/bbatsov/rubocop#setting-the-target-ruby-version

Some checks are dependent on the version of the Ruby interpreter which the inspected code must run on. For example, using Ruby 2.0+ keyword arguments rather than an options hash can help make your code shorter and more expressive... unless it must run on Ruby 1.9.

Let RuboCop know the oldest version of Ruby which your project supports with:

```yaml
AllCops:
  TargetRubyVersion: 1.9
```
