### ISSUE TITLE
Validate metadata.json

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#155]
I broke a release because I killed the metadata.json :(

https://travis-ci.org/voxpupuli/puppet-gluster/jobs/129490036

We should get $something to validate it.

**Comment by jyaworski** [comment]
Isn't there a metadata_lint task?

**Comment by bastelfreak** [comment]
I just checked it. the metadata_lint task is enabled. but it seems to not catch the error :(

**Comment by 3flex** [comment]
FYI I've created a PR at https://github.com/voxpupuli/metadata-json-lint/pull/25 which would mean the version_requirement is tested correctly and would pick up on this issue. This issue can be closed if that is released.

**Comment by 3flex** [comment]
https://github.com/voxpupuli/metadata-json-lint/pull/25 was merged, can this be closed?

**Comment by juniorsysadmin** [comment]
Closing, because https://github.com/voxpupuli/metadata-json-lint/pull/25 is in a release
