### ISSUE TITLE
use Style/RegexpLiteral correctly

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#168]
we enable Style/RegexpLiteral in our rubocop config. this cop has a few possible stlyes that you have to enfoce with EnforcedStyle which we don't do. this often results in a cop loop. I  prefer `EnforcedStyle: percent_r`, any other opinions?

documentation at http://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/RegexpLiteral

**Comment by rnelson0** [comment]
While I personally prefer `percent_r`, I think most every other developer I've met prefers `slashes`. Also, why doesn't `mixed` work with both? *sigh* Rubocop.

**Comment by bastelfreak** [comment]
I prefed slashes some time ago, but escaping changed my mind, thats why I vote for percent_r.

**Comment by rnelson0** [comment]
I am concerned how it might affect those contributing to us, they'll need to do more rebases likely and it could put some people off.

**Comment by jyaworski** [comment]
I vote for percent_r for the same reasons, although // is more pleasant.

**Comment by juniorsysadmin** [comment]
I prefer ```percent_r```

**Comment by bastelfreak** [comment]
We got a few opinions here and it seems to tend to percent_r. I created a PR for that.

**Comment by Sharpie** [comment]
Way late to this party. But, I personally prefer `slashes` because the Puppet language syntax has no `percent_r` equivalent. Preferring `slashes` results in regex literals that are consistent between both the Ruby and Puppet code in a module --- which can help newcomers that have a contribution that involves both languages.

`percent_r` is useful in situations where it avoids escaping.

**Comment by op-ct** [comment]
Retroactive 👍 for `percent_r`.  Forward slashes are common in Puppet-related code, and escaping URLs or file paths usually makes a regex look like an extra-hard excite bike stage.

It's unfortunate the Puppet language itself doesn't support `%r`, because it provides a lot of clarity in Ruby.
