### ISSUE TITLE
Add modulesync version number to modules when updated

### ISSUE THREAD

**Issue by bbriggs** [voxpupuli/modulesync_config#184]
In order to keep track of what version of modulesync was used on a given module, we should use a key/value pair somewhere in the repo's root that we can query. When paired with a version-bump script that keeps the msync version file in line with the tag/release version, this would be a more reliable method than depending on commit messages.

**Comment by rski** [comment]
Seconded, mostly because I always forget to even mention it in the commit message.

**Comment by dhoppe** [comment]
Is not this already fixed via #193?

**Comment by bbriggs** [comment]
we merged a PR for this forever ago. We can close this.
