### ISSUE TITLE
create a 'awesome-enterprise-wescale-super-config'

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#187]
One config file to rule them all!

I talked to @nibalizer in the past about this and yesterday again. We've several config files that hold the name and a bit of configuration of our modules. For example the managed_modules.yml in this repo, the modules file in the plumbing repo and the repos hash in config.py.erb in pcci-configuration.

We should try to unite this into a single place, maybe modulesync_config or plumbing? And them try to get rid of the other files or generate them (we need a single source of truth). We created a draft for a new file [here](https://etherpad.openstack.org/p/voxpupuli-brainstorm). We now also have a .pcci.yml which should be generated based on the new config thing.

**Comment by ekohl** [comment]
I think this is now irrelevant. Except for the PDK modules, everything is now managed in modulesync_config. I'd propose to store them all there (https://github.com/voxpupuli/pdk-templates/issues/3)
