### ISSUE TITLE
fix ruby1.9 testsuite?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#198]
We're currently using the latest rspec-rubocop release. They dropped ruby1.9 support a few days back. We probably need to pin it, would be cool if we can only pin it for ruby1.9.

**Comment by jk2l** [comment]
updating it to this seem to fix it. and travis run on rubocop can only set it to run in 2.0.0+ version so it shouldn't break anything

`gem 'rubocop-rspec', '~> 1.5',                                    :require => false if RUBY_VERSION >= '2.0.0'`

**Comment by bastelfreak** [comment]
merged
