### ISSUE TITLE
extend rspec_helper with to use rspec-puppet-facts

### ISSUE THREAD

**Issue by igalic** [voxpupuli/modulesync_config#23]
our spec/spec_helper.rb should `require 'rspec-puppet-facts'`, and 'include RspecPuppetFacts`

**Comment by igalic** [comment]
… and then we should start using it in our spec tests :)

**Comment by electrical** [comment]
Just a word of warning of my own experience.
Ensure you only loop tests that are actually platform dependent.
I overlooked that fact initially and caused a horrible explosion of tests and runtime.

As an example after refactoring the runtime of a single file went from 10 minutes to 30 seconds :-)

**Comment by igalic** [comment]
whoa…
thanks :D

**Comment by jyaworski** [comment]
This was done at some point. Closing.
