### ISSUE TITLE
Deal with multiple CONTRIBUTING.md

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/modulesync_config#252]
In the past, modulesync_config wrote a `CONTRIBUTING.md` do the modules root. We changed that to `.github/CONTRIBUTING.md`, but never purged the old files. We migrated a huge amount of modules in the past, and they still contain their original `CONTRIBUTING.md`. We should decide if we want to manage both, if they should be equal.

**Comment by igalic** [comment]
do we have a general documentation for how we're dealing with sync'ed files?

**Comment by bastelfreak** [comment]
I am not sure if I understand the question. Do you mean files that we synced in the past but not don't sync anymore? No docs yet . AFAIK this is the first case where we 'unmage' a file.

**Comment by igalic** [comment]
well, we have a general aproach to unmanaging files via .sync.yml
i meant more, documentation for: "when you submit to the holy sync, this is what's affected"

**Comment by wyardley** [comment]
To me, having a CONTRIBUTING.md in the main root directory is probably where people are going to look for info on how to contribute, and I think it makes sense to use the same one for most (all?) voxpupuli modules. Whether it should be exactly the same file as the one in .github, I'm not as sure, presumably, the latter is mostly to make sure someone sees our boilerplate when opening a new PR, whereas the former is mostly helpful in terms of getting people the information they need to create a PR in the first place... Just my $0.02

**Comment by wyardley** [comment]
@voxpupuli/collaborators Can we have some more discussion about this or get a decision made?
Does `.github/CONTRIBUTING.md` do anything special that won't work if it's in the root directory?

It seems like the root directory is one of the acceptable options:
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

Right now, we have the issue of the possibility of drift if we copy the file into the root directory but don't modulesync it later.

**Comment by TraGicCode** [comment]
@bastelfreak Yes i'm a little confused.  Why is this in the .github folder.  This doesn't seem very "conventional".

**Comment by roidelapluie** [comment]
proper way to do this is to implement absence of files in msync

**Comment by wyardley** [comment]
@roidelapluie I think the bigger point is where the CONTRIBUTING file should go... I would argue that no one is going to see it in `.github/`, so I think the current location is the bigger problem than the fact that some modules have 2.

If we standardize on something, it should be very easy to make sure it exists in one place or not the other (we might also have to clean up / update any references to the previous path).

Since Github mentions top level as a valid directory, is there any opposition to moving our primary `CONTRIBUTING.md` to the root directory (and in the process, wiping out any pre-existing ones), and then wipe out the one in `.github`?

**Comment by dhoppe** [comment]
I think we should add a section to the ```README.md``` where we place a link to ```.github/CONTRIBUTIN.md```. 

Some modules already do this:
* https://github.com/voxpupuli/puppet-grafana/blob/master/README.md#development

**Comment by ekohl** [comment]
cf79d3873b09dd4187e9d1de99d865bd7d0d2203 fixed this, right?

**Comment by bastelfreak** [comment]
you're correct, it's now solved.
