### ISSUE TITLE
Use github_changelog_generator for changelogs

### ISSUE THREAD

**Issue by rnelson0** [voxpupuli/modulesync_config#268]
http://rubygems.org/gems/github_changelog_generator has worked out great with some other tools, we should use it here.

**Comment by alexjfisher** [comment]
I think this sort of tool can be a very good starting point, but some manual editing afterwards always produces a better result.  For instance, I don't need 6 different 'modulesync' entries per release when a nice explanation about VP's modulesync process in some sort of header is so much nicer.  Also, what are the breaking changes?  As a user, what's likely to be important to me?

That said, maybe some of these issues are fixable. It looks like it's possible to use labels to influence the tool's output.

https://github.com/skywinder/Github-Changelog-Generator#features-and-advantages-of-this-project
> Manually include or exclude issues by labels

**Comment by dhoppe** [comment]
@rnelson0 I would love to see this in action. It should be great in combination with labels and proper commit messages.

**Comment by juniorsysadmin** [comment]
I would be cautious about any enforcement of commit message style - we want to make contributions easy to make not harder.

**Comment by alexjfisher** [comment]
Does it use the commit message, or the PR title?  The latter can be edited even after the PR is merged.

**Comment by rnelson0** [comment]
PR title. I've done a few releases now with r10k using this, and also puppet-lint if we would like to use this with Ruby gems. It does require a bit of issues/pr cleanup. I generate the changelog, then review all closed issues/pr to mark modulesync/duplicate/invalid/wontfix to prevent those from showing in the changelog, and update any titles as needed. Generate the changelog again and make sure it's trimmed up, thenncommit and go. If we try and keep up with that on an ongoing basis, it won't add that much effort. and it's just a rake task to use - but of course, you don't NEED to use it on a given module if you don't want.

We could either deploy it in modulesync, to all modules, or maintain the settings somewhere to be added to individual repo's .sync.yml or such. Any thoughts on that?

**Comment by wyardley** [comment]
This is now in place, and we also have a way to suppress entries. I think there's still some work on having a separate section for breaking changes, but I think we can close the issue.
