### ISSUE TITLE
CentOS-5 Nodeset Retirement CentOS 5 EOL  March 31st, 2017

### ISSUE THREAD

**Issue by sacres** [voxpupuli/modulesync_config#293]
As per: [CentOS 5 EOL](https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d) . 
We should plan to remove the CentOS-5 nodesets, yes?

**Comment by juniorsysadmin** [comment]
YesNo. The bigger question is: Should we be dropping support for certain operating systems in modules when they go End of Life ?

**Comment by sacres** [comment]
I vote +1 to drop. EOL is a fairly static concept.

**Comment by vinzent** [comment]
remove operating systems from supported OS'es when they reached EOL - not only restricted to CentOS.

**Comment by sacres** [comment]
Yes, that as well @vinzent. I presented this specific use-case as it's immediately relevant as well as a pathway to standardizing this process.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/modulesync_config/pull/425 adds tooling to easily do this.

**Comment by bastelfreak** [comment]
This can now be closed. We dropped the docker nodesets in the last modulesync run (today). Also RHEL 5 got removed from all metadata.json files.

**Comment by ekohl** [comment]
@bastelfreak did the nodesets actually got removed? AFAIK modulesync doens't remove files when they become unmanaged. I have a bunch of commits ready that I haven't pushed yet but they're nothing special. Assuming clean up to date checkouts:

```
for module in modules/* ; do
( cd $module && git checkout -b remove-docker-nodesets && git rm -r spec/acceptance/nodesets/docker && git commit -av -m "Remove docker nodesets && git push origin HEAD -u && hub pull-request -m "Remove docker nodesets" )
done
```

There is also some special care that some windows modules need to remove https://github.com/voxpupuli/puppet-windows_env/blob/3176c2fdbe611bad6725144f2060a397513145ca/.sync.yml#L4-L19. A last mention is that I think puppet-fail2ban and puppet-puppetserver both haven't been converted.

**Comment by bastelfreak** [comment]
I made some false assumptions about the cleanup script. The nodesets are present but we removed RHEL 5 from the metadata.json (and all other EOL operating systems)
