### ISSUE TITLE
Only include the correct nodesets depending on the module's supported O/S

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/modulesync_config#385]
It would be nice to have windows and/or linux node sets included with modules when they support the given platform.  For Example, It doesn't make sense to have linux node sets with a module that will only ever work on windows and it's not really feasable and/or maintainable to add the exclusion of all the nodesets to the module's .sync.yaml.  I propose we do the following which is what puppetlabs is currently doing in their modulesync configs

https://github.com/puppetlabs/modulesync_configs/blob/d1f5f9caf0607e707eeed4e95f6a957e6dcaa8df/config_defaults.yml#L1-L46

**Comment by bastelfreak** [comment]
It is a good idea to clean this up and only apply nodesets that actually work. I'm not sure about the best way to do this. My main concern is described in #187. The puppetlabs approach would add another list of modules that we need to maintain.

**Comment by ekohl** [comment]
76e6cb2b1437375fef21cc53886e08a083794314 removed the last nodeset. We're now only relying on beaker-hostgenerator.
