### ISSUE TITLE
Make Tests & Test Coverage Changes visible in a PR Conversation

### ISSUE THREAD

**Issue by TraGicCode** [voxpupuli/modulesync_config#386]
We should all advocate that any new feature or even bug fix should be accompanied by tests in order to prevent regression and prove something is indeed doing as we expect.  We are also outnumbered by the # of issues and PR's being opened and this will only get worse. 

That being said, we should make it visible within the PR's conversation that:
1.) Tests were not added/removed to this PR's changes
2.) Did Test coverage go up or down?

This will also help speed up OUR review process if we can see this visibility to understand the impact of the change and also prevent us from wasting time checking to see if tests were added or not.

An Examples below: ( These don't show test additions or adds just coverage deltas. )

https://github.com/PowerShell/xFailOverCluster/pull/145
https://github.com/rodjek/rspec-puppet/pull/608

/cc @voxpupuli/collaborators for feedback 🗡

**Comment by rnelson0** [comment]
I feel (literally feel, no evidence to back this up) that most of the time, reviewers do ask for tests before merging or submit a second PR with tests when necessary. But of course, that depends on the reviewer, and perhaps observation would show that's not the case!

Is there a specific suggestion for how to encourage more advocacy for tests, something you'd like to see us change?

**Comment by TraGicCode** [comment]
I'm just mainly looking to introduce automation to speed up the review process and provide information to the reviewer and the person creating the PR to know exactly the impact of their changes.

Just some thoughts and ideas.

**Comment by bastelfreak** [comment]
It may be helpful to report the test coverage into the PR. As far as I know the coverage reports from rspec-puppet are often inaccurate. It would be nice if somebody can investigate into coveralls + rspec-puppet. If that is useable we can maybe let it report into the PR, if people are ok with it? (I am ok with it)

**Comment by juniorsysadmin** [comment]
Being outnumbered by issues/PRs is another topic entirely with many factors (quality of modules when they are imported, no 'primary' maintainer for a specific modules who cares enough about it to keep it useful for current needs, decrease in popularity of Puppet, slow closing of PRs with no response, etc). I think we do a pretty good job of pushing for additional tests where needed, without blocking small, low-risk PRs from being merged.

**Comment by ekohl** [comment]
> It may be helpful to report the test coverage into the PR. As far as I know the coverage reports from rspec-puppet are often inaccurate. It would be nice if somebody can investigate into coveralls + rspec-puppet. If that is useable we can maybe let it report into the PR, if people are ok with it? (I am ok with it)

The reality is that a one-line change won't change coverage but can fix a bug. I can't think of an automated way that always works. Coveralls also spams a lot because of all the comments. Due to the huge number of changes I already sometimes just delete them all voxpupuli github notifications. Let's not make it worse.

> Being outnumbered by issues/PRs is another topic entirely with many factors (quality of modules when they are imported, no 'primary' maintainer for a specific modules who cares enough about it to keep it useful for current needs, decrease in popularity of Puppet, slow closing of PRs with no response, etc). I think we do a pretty good job of pushing for additional tests where needed, without blocking small, low-risk PRs from being merged.

Agreed on this.

**Comment by TraGicCode** [comment]
Sounds like it's not really worth the effort.  I'm going to close this :) thanks for everyone participating and giving feedback!
