### ISSUE TITLE
YAML test

### ISSUE THREAD

**Issue by millerjl1701** [voxpupuli/modulesync_config#393]
In looking through closed issues, it doesn't appear that YAML linting has been considered before. My wife ran across a gem (yaml-lint) that seemed to do the job, and I recently added it to my puppet-skeleton for puppet4/5 module development in order to figure out if/how it works.  With the advent of hiera 5, more and more yaml files are going to be present. Thoughts on adding it? The major downside I see is that it hasn't been updated in a while (https://rubygems.org/gems/yaml-lint/) and may not be suitable.

**Comment by bastelfreak** [comment]
Hi @millerjl1701, thanks for this request. Linting them is a good idea. Do you know if hiera itself has a validation option that we could use?

**Comment by millerjl1701** [comment]
Good question. No, first google hit looks promising (https://ask.puppet.com/question/11000/does-puppet-provide-a-validationsyntax-checker-for-hiera/) concerning that topic. I'll read through that and some other results here later. There might be a couple of ways to do this besides the gem option.

**Comment by millerjl1701** [comment]
@bastelfreak , I didn't find anything with hiera itself to check syntax. Reading through the options presented in the ask.puppet link, methods presented were:

- using "ruby -e "require ;yaml'; YAML.load_file('$file')" for a file or directory
- bash wrapper scripts that do the above
- using the Kwalify gem to create a schema to validate hiera yaml
- using the yaml-lint gem mentioned when I opened the issue

In looking through the yaml-lint ruby code, it is using the ruby command above and catching errors or reporting success... effectively doing the same thing as the bash script wrappers mentioned in the ask.puppet article.

Digging further,  it looks like this was discussed in the puppet-syntax project prior: https://github.com/voxpupuli/puppet-syntax/issues/39 which was discussed further in: https://logicminds.github.io/blog/2016/01/16/testing-hiera-data/

So, based on that, perhaps no further action is required at this point and the issue be closed? If there isn't a way to create a valid test, no reason to spend the cycles on it.
