### ISSUE TITLE
Remove EOL Operatingsystems

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/modulesync_config#426]
* [x] https://github.com/voxpupuli/puppet-autofs/pull/86
* [x] https://github.com/voxpupuli/puppet-collectd/pull/733
* [x] https://github.com/voxpupuli/puppet-letsencrypt/pull/106
* [x] https://github.com/voxpupuli/puppet-network/pull/234
* [x] https://github.com/voxpupuli/puppet-nginx/pull/1153
* [x] https://github.com/voxpupuli/puppet-nodejs/pull/341
* [ ] https://github.com/voxpupuli/puppet-nscd/pull/25
* [x] https://github.com/voxpupuli/puppet-rabbitmq/pull/666
* [x] https://github.com/voxpupuli/puppet-report_hipchat/pull/33
* [x] https://github.com/voxpupuli/puppet-squid/pull/75
* [ ] https://github.com/voxpupuli/puppet-zabbix/pull/467
* [ ] voxpupuli/puppet-alternatives
* [ ] voxpupuli/puppet-archive
* [ ] voxpupuli/puppet-autofs
* [ ] voxpupuli/puppet-boolean
* [ ] voxpupuli/puppet-cassandra
* [ ] voxpupuli/puppet-collectd
* [ ] voxpupuli/puppet-community_kickstarts
* [ ] voxpupuli/puppet-confluence
* [ ] voxpupuli/puppet-dhcp
* [ ] voxpupuli/puppet-drbd
* [ ] voxpupuli/puppet-etherpad
* [ ] voxpupuli/puppet-extlib
* [ ] voxpupuli/puppet-grafana
* [ ] voxpupuli/puppet-healthcheck
* [ ] voxpupuli/puppet-hiera
* [ ] voxpupuli/puppet-jira
* [ ] voxpupuli/puppet-jolokia
* [ ] voxpupuli/puppet-kafka
* [ ] voxpupuli/puppet-letsencrypt
* [ ] voxpupuli/puppet-logrotate
* [ ] voxpupuli/puppet-make
* [ ] voxpupuli/puppet-mcollective
* [ ] voxpupuli/puppet-minecraft
* [ ] voxpupuli/puppet-mongodb
* [ ] voxpupuli/puppet-mumble
* [ ] voxpupuli/puppet-mysql_java_connector
* [ ] voxpupuli/puppet-network
* [ ] voxpupuli/puppet-nginx
* [ ] voxpupuli/puppet-nodejs
* [ ] voxpupuli/puppet-nscd
* [ ] voxpupuli/puppet-openvpn
* [ ] voxpupuli/puppet-php
* [ ] voxpupuli/puppet-prometheus
* [ ] voxpupuli/puppet-prometheus_reporter
* [ ] voxpupuli/puppet-proxysql
* [ ] voxpupuli/puppet-puppetboard
* [ ] voxpupuli/puppet-puppetserver
* [ ] voxpupuli/puppet-rabbitmq
* [ ] voxpupuli/puppet-report_hipchat
* [ ] voxpupuli/puppet-sftp_jail
* [ ] voxpupuli/puppet-splunk
* [ ] voxpupuli/puppet-squid
* [ ] voxpupuli/puppet-staging
* [ ] voxpupuli/puppet-stash
* [ ] voxpupuli/puppet-system
* [ ] voxpupuli/puppet-tvheadend
* [ ] voxpupuli/puppet-unattended_upgrades
* [ ] voxpupuli/puppet-virtualbox
* [ ] voxpupuli/puppet-zabbix

**Comment by bastelfreak** [comment]
Today I run [your script](https://github.com/voxpupuli/modulesync_config/blob/master/bin/clean-metadata) against all modules. They should now all have the correct puppet version dependency and also only supported operating systems.
