### ISSUE TITLE
Run acceptance tests against all supported operatingsystems

### ISSUE THREAD

**Issue by ekohl** [voxpupuli/modulesync_config#428]
* [ ] https://github.com/voxpupuli/puppet-autofs/pull/85
* [ ] https://github.com/voxpupuli/puppet-collectd/pull/732
* [ ] https://github.com/voxpupuli/puppet-corosync/pull/426
* [ ] https://github.com/voxpupuli/puppet-gluster/pull/144
* [x] https://github.com/voxpupuli/puppet-nscd/pull/24
* [x] https://github.com/voxpupuli/puppet-report_hipchat/pull/32
* [x] https://github.com/voxpupuli/puppet-yum/pull/79

**Comment by bastelfreak** [comment]
I just had a discussion with @baurmatt about this. Maybe it would be cool to check all OSes in the metadata.json in an msync run and update the .sync.yml / .travis.yml with suitable beaker jobs.

**Comment by dhoppe** [comment]
This could be difficult, because there are a lot of metadata.json which do not provide a version for ArchLinux or FreeBSD etc.

**Comment by baurmatt** [comment]
So how about a whitelist for OS/Version which are, in general, known to work? Special OS like Arch, Gentoo, FreeBSD, Windows, Raspbian need to be managed manually until we figure something out for them.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/modulesync/pull/168 should allow looking at metadata.json. We can then write a method that automatically maps things and skips unknown ones.

**Comment by ekohl** [comment]
This is now done.
