### ISSUE TITLE
streamline release process

### ISSUE THREAD

**Issue by igalic** [voxpupuli/modulesync_config#45]
- [x] make module: rake tasks invisible by default
- [x] change travis_release to a more speaking name like, puppet_community_release
- [x] after module:bump_commit, puppet_community_release should append -rc to our metada.json version

**Comment by rnelson0** [comment]
I think I see how the last step works, but can you elaborate on the desired workflow?

If it's what I think, the rake task that travis calls should check for `-rc` and call it a day if it finds it, rather than wasting time erroring out at the forge (I hope that errors!).

**Comment by igalic** [comment]
i very much hope that blacksmith's `module:bump` does the sensible thing and makes `1.2.3-rc` into `1.2.4`, if not, that's a bug in the semver gem.

**Comment by igalic** [comment]
all done as per https://github.com/puppet-community/puppet-community.github.io/issues/21
we're now trying to figure out if that works.
unfortunately, it appears to require a working ruby :D

**Comment by igalic** [comment]
after the (two;) successful release(s) of puppet-extlib (https://github.com/voxpupuli/puppet-extlib/pull/45 & https://github.com/voxpupuli/puppet-extlib/pull/43) we should migrate the rake task into this repository. (see also https://github.com/voxpupuli/puppet-blacksmith/issues/25 )

**Comment by rnelson0** [comment]
Actually, I'd love to have this option for my own modules. Could it be put into a ruby gem and included via Gemfile and spec/spec_helper.rb?

**Comment by igalic** [comment]
i thought about making it a task of blacksmith, but i'm not sure that's a good idea…

**Comment by rnelson0** [comment]
Probably not since it hides some tasks. But as a standalone that requires
blacksmith it could be useful when someone wants to opt in

-- 

Rob Nelson
rnelson0@gmail.com

**Comment by igalic** [comment]
*nod* thanks for the feedback here, @rnelson0!

**Comment by igalic** [comment]
i think this is solid by now and can be closed
