### ISSUE TITLE
Add .pmtignore

### ISSUE THREAD

**Issue by liamjbennett** [voxpupuli/modulesync_config#49]
Have we thought about adding this file? Seems useful.

http://rnelson0.com/2015/11/15/exclude-files-from-a-puppet-module-release/

**Comment by igalic** [comment]
iirc, we just added the necessary ignores to .gitignore

**Comment by rnelson0** [comment]
PMT doesn't use the same format, I've filed a bug for it. I believe it's
okay if the git ignore statement does not have a leading slash.

On Tuesday, December 22, 2015, Igor Galić <notifications@github.com> wrote:

> iirc, we just added the necessary ignores to .gitignore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/puppet-community/modulesync_config/issues/49#issuecomment-166619779>
> .
>


-- 

Rob Nelson
rnelson0@gmail.com

**Comment by igalic** [comment]
which we do not.
