### ISSUE TITLE
Restrict continuous-integration/travis-ci/push to only the master branch

### ISSUE THREAD

**Issue by igalic** [voxpupuli/modulesync_config#50]
as per https://github.com/puppet-community/puppet-archive/pull/102#merged-event

**Comment by rnelson0** [comment]
Bump. Does anyone have objections to adding this to the default `.travis.yml`?

**Comment by ffrank** [comment]
👍 make it so

**Comment by igalic** [comment]
done?

**Comment by rski** [comment]
Right now there is 2x the build for modulesync, one for the msync branch and one for the PR opened. This is a waste that costs us a lot of time waiting for CI, we should do this.
