### ISSUE TITLE
Support rvm 1.8.7

### ISSUE THREAD

**Issue by juniorsysadmin** [voxpupuli/modulesync_config#61]
Currently if rvm 1.8.7 is listed in travis.yml, builds for it will fail due to one or more dependent gems requiring Ruby 1.9.3 or above.

**Comment by rnelson0** [comment]
Given that PL is no longer testing modules on 1.8.7, and 1.8.7 is now 18 months past [extended EOS](https://www.ruby-lang.org/en/news/2014/07/01/eol-for-1-8-7-and-1-9-2/), it has seemed safe to remove 1.8.7 from the matrix. 1.8.7 is not in the general config that I can see. Is this issue on the config or restricted to individual modules?

**Comment by jyaworski** [comment]
I would be against adding 1.8.7 support. Anyone on an OS that packages 1.8.7 (like RHEL6) can get around it by using Puppetserver, which bundles JRuby (1.9.3). It's what I'm doing.

**Comment by juniorsysadmin** [comment]
>  Is this issue on the config or restricted to individual modules?

@rnelson0 Restricted to individual modules that are in the voxpupuli namespace at the moment.

**Comment by juniorsysadmin** [comment]
Closing due to overwhelming lack of support for the idea.
