### ISSUE TITLE
'noop' should be the default

### ISSUE THREAD

**Issue by trevor-vaughan** [voxpupuli/modulesync_config#644]
Being new to the Vox community, I've found that the primary use case using `msync` revolved around adding `--noop` to my commands more often than not.

As such, I would like to propose that `--noop` become the default and something like `--apply` or `--push` become a new option.

**Comment by ekohl** [comment]
I feel this mirrors my own experience, though I also very often use `--offline` to avoid all the git actions. For me a `template` subcommand that only renders the templates might also make sense.

**Comment by ekohl** [comment]
Looking at this further, did you mean to submit this to https://github.com/voxpupuli/modulesync instead of our config?
