### ISSUE TITLE
Add puppet-lint github action?

### ISSUE THREAD

**Issue by jcpunk** [voxpupuli/modulesync_config#671]
Would it be worth adding the puppet-lint github action to the default workflow for voxpupuli modules?

https://github.com/marketplace/actions/puppet-lint-action

**Comment by ekohl** [comment]
No, it doesn't. It's part of the Travis config and already runs. That action in particular uses a pre-built container and only runs `puppet-lint` in it. That means we don't get the plugins that we rely on.

**Comment by jcpunk** [comment]
Interesting.

I've been opening PRs that resolve puppet-lint issues I've randomly discovered in various voxpupuli modules the last few days.  Is Travis only checking changed lines?

**Comment by ekohl** [comment]
It shouldn't, but not all modules are in sync with our current best practices (first check if there's a modulesync PR open). Another thing is that if you have some plugins in ~`/.gem`, it doesn't mean we are using them in our modules. Those are some things you may see.
